version: '3.9'

services:
  web:
    build: .
    context: ./web
    ports:
      - "5173:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass d12
    volumes:
      - redisData:/data
  server:
    build: .
    context: ./server
    ports: 
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=d12
      - CACHE_TTL=60
      - MAX_ITEM_IN_CACHE=1000
      - PORT=8080
      - TOKEN_SECRET=953f8c1a6dd856
volumes:
  redisData:
